### PR TITLE
Add docs for InputMap

### LINKED ISSUE #1: [Features] Add possibility of classic W,A,S,D for movement
Would it be possible to add this type of configuration for the movement?

### PR DESCRIPTION
**Pull request by j8r**
In a way, resolves #1 .

### CODE REVIEW

**Comment by j8r** [comment]
I noticed another `README.md` like the top level one in the `assets/maujoe.camera_control` directory. (same for `LICENSE.md`)

More importantly, the directory is named `assets` - but this are gdscript scripts, not assets, which are usually [images, audio or scenes](https://docs.godotengine.org/en/stable/getting_started/workflow/assets/index.html).

In my opinion, this organization can simplified by just having the files inside `maujoe.camera_control` at the top-level.

**Comment by Maujoe** [comment]
Sorry for the delay and thanks for the interest. I think the topic of this issue was how to set actions in generel which works fine with godots InputMap.

The snippet works but it's more for advanced use cases and such users probably already know how to do it. I think the hint with the "project settings menu: Project> Project Settings> Input Map" in the readme would be enough for the default use case.
EDIT: Okay I changed my mind if you add it to the second readme too then I am fine with it.

> I noticed another `README.md` like the top level one in the `assets/maujoe.camera_control` directory. (same for `LICENSE.md`)
> 
This is correct the files in the root directory are mostly for Github but they get possibly replaced by other plugins or the user so there are seperate ones in the assets folder. I have no problem with that.

> More importantly, the directory is named `assets` - but this are gdscript scripts, not assets, which are usually [images, audio or scenes](https://docs.godotengine.org/en/stable/getting_started/workflow/assets/index.html).
> 
Yes I understand the argument I will rename it to "addons" with the next update this is also more common.

> In my opinion, this organization can simplified by just having the files inside `maujoe.camera_control` at the top-level.

I want to keep the current structure because many plugins use the "addons" (assets) folder, the advantage is there's a common folder for third party stuff and the root folder get not messed up by them. :)

**Comment by j8r** [comment]
> I want to keep the current structure because many plugins use the "addons" (assets) folder, the advantage is there's a common folder for third party stuff and the root folder get not messed up by them. :)

Not sure to get it, this is a library - not a project. I cloned this one with `git subtree`, so the whole project for me is inside a `thirdparty` (or whatever) directory, similarly to the [Godot Project](https://github.com/godotengine/godot/tree/master/thirdparty).

Is it a library or a project?

It looks like a template, but sorry I don't how it is useful, a project examples could perfectly be in a `examples` folder.

**Comment by j8r** [comment]
> I want to keep the current structure because many plugins use the "addons" (assets) folder, the advantage is there's a common folder for third party stuff and the root folder get not messed up by them. :)

Not sure to get it, this is a library - not a project (right?). I cloned this one with `git subtree`, so the whole project for me is inside a `thirdparty` (or whatever) directory, similarly to the [Godot Project](https://github.com/godotengine/godot/tree/master/thirdparty).

It looks like a template, but sorry I don't know how it is useful, a project examples could perfectly be in a `examples` folder.

**Comment by j8r** [comment]
After looking at some [plugins](https://github.com/Calinou/awesome-godot#plugins-and-scripts), it seems that the `addons` directory is sometimes used.

I don't really understand, but I you like that , I'm ok. It just adds more path to include the script, and a bit confusing to what LICENSE or README.md to refer.

**Comment by j8r** [comment]
After looking at some [plugins](https://github.com/Calinou/awesome-godot#plugins-and-scripts), it seems that the `addons` directory is sometimes used.

I don't really understand, but if you like I'm ok. It just adds more path to include the script, and a bit confusing to what LICENSE or README.md to refer.

EDIT: just read https://godotengine.org/article/plugins, got it for the `addons` directory, but anyone wanting to use git submodule/subtree will have to use symlinks, or vendoring :(

**Comment by Maujoe** [comment]
Ah okay now I understand. I haven't used submodule for godot projects yet but it's sounds cumbersome for submodule user. 

The problem is that the Godot's builtin asset libary put everything in the main directory. I think there was a discussion about that somewhere but currently it's preferred to structure addons this way so I will stick with that for now. :/

**Comment by j8r** [comment]
Do you think a symlink is fine for README and LICENSE, or do you prefer to duplicate?

**Comment by j8r** [comment]
Just tried to install an asset from the `Asset Lib` button. Too bad it does not fit well with git, and I don't see how to upgrade.

Anyway, I pushed changes.

**Pull request merged**
